const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('browserAPI', {
  getInitialState: () => ipcRenderer.invoke('get-initial-state'),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  updateSettings: (updates) => ipcRenderer.invoke('update-settings', updates),
  getPrivacySettings: () => ipcRenderer.invoke('get-privacy-settings'),
  toggleTrackerBlocking: () => ipcRenderer.invoke('toggle-tracker-blocking'),
  toggleFingerprintNoise: () => ipcRenderer.invoke('toggle-fingerprint-noise'),
  toggleThirdPartyCookies: () => ipcRenderer.invoke('toggle-third-party-cookies'),
  toggleDnt: () => ipcRenderer.invoke('toggle-dnt'),
  toggleHttpsUpgrade: () => ipcRenderer.invoke('toggle-https-upgrade'),
  blockDomain: (domain) => ipcRenderer.invoke('block-domain', domain),
  unblockDomain: (domain) => ipcRenderer.invoke('unblock-domain', domain),
  addBookmark: (bookmark) => ipcRenderer.invoke('add-bookmark', bookmark),
  updateBookmark: (id, updates) => ipcRenderer.invoke('update-bookmark', id, updates),
  removeBookmark: (id) => ipcRenderer.invoke('remove-bookmark', id),
  searchBookmarks: (query) => ipcRenderer.invoke('search-bookmarks', query),
  getBookmarks: () => ipcRenderer.invoke('get-bookmarks'),
  addHistory: (entry) => ipcRenderer.invoke('add-history', entry),
  searchHistory: (query) => ipcRenderer.invoke('search-history', query),
  clearHistory: () => ipcRenderer.invoke('clear-history'),
  deleteHistoryEntry: (id) => ipcRenderer.invoke('delete-history-entry', id),
  getHistory: () => ipcRenderer.invoke('get-history'),
  addDownload: (d) => ipcRenderer.invoke('add-download', d),
  updateDownload: (id, u) => ipcRenderer.invoke('update-download', id, u),
  removeDownload: (id) => ipcRenderer.invoke('remove-download', id),
  getDownloads: () => ipcRenderer.invoke('get-downloads'),
  addPassword: (p) => ipcRenderer.invoke('add-password', p),
  getPasswords: () => ipcRenderer.invoke('get-passwords'),
  updatePassword: (id, u) => ipcRenderer.invoke('update-password', id, u),
  removePassword: (id) => ipcRenderer.invoke('remove-password', id),
  addToReadingList: (item) => ipcRenderer.invoke('add-reading-list', item),
  removeFromReadingList: (id) => ipcRenderer.invoke('remove-reading-list', id),
  getReadingList: () => ipcRenderer.invoke('get-reading-list'),
  showSaveDialog: (options) => ipcRenderer.invoke('show-save-dialog', options),
  showOpenDialog: (options) => ipcRenderer.invoke('show-open-dialog', options),
  getUserDataPath: () => ipcRenderer.invoke('get-user-data-path'),
  getDownloadsPath: () => ipcRenderer.invoke('get-downloads-path'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  openPath: (p) => ipcRenderer.invoke('open-path', p),
  showItemInFolder: (p) => ipcRenderer.invoke('show-item-in-folder', p),
  clipboardWriteText: (text) => ipcRenderer.invoke('clipboard-write-text', text),
  clipboardReadText: () => ipcRenderer.invoke('clipboard-read-text'),
  clipboardWriteImage: (dataUrl) => ipcRenderer.invoke('clipboard-write-image', dataUrl),
  getPlatform: () => ipcRenderer.invoke('get-platform'),
  setZoom: (level) => ipcRenderer.invoke('set-zoom', level),
  printPage: () => ipcRenderer.invoke('print-page'),
  savePage: () => ipcRenderer.invoke('save-page'),
  setFullscreen: (flag) => ipcRenderer.invoke('set-fullscreen', flag),
  isFullscreen: () => ipcRenderer.invoke('is-fullscreen'),
  getExtensions: () => ipcRenderer.invoke('get-extensions'),
  installExtension: (extPath) => ipcRenderer.invoke('install-extension', extPath),
  uninstallExtension: (id) => ipcRenderer.invoke('uninstall-extension', id),
  toggleExtension: (id) => ipcRenderer.invoke('toggle-extension', id),
  showNotification: (opts) => ipcRenderer.invoke('show-notification', opts),
  setProxy: (config) => ipcRenderer.invoke('set-proxy', config),
  clearBrowsingData: (dataTypes) => ipcRenderer.invoke('clear-browsing-data', dataTypes),
  getBatteryInfo: () => ipcRenderer.invoke('get-battery-info'),
  getSystemInfo: () => ipcRenderer.invoke('get-system-info'),
  writeFile: (fp, data) => ipcRenderer.invoke('write-file', fp, data),
  readFile: (fp) => ipcRenderer.invoke('read-file', fp),
  getSystemFonts: () => ipcRenderer.invoke('get-system-fonts'),
  windowMinimize: () => ipcRenderer.send('window-minimize'),
  windowMaximize: () => ipcRenderer.send('window-maximize'),
  windowClose: () => ipcRenderer.send('window-close'),
  windowIsMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  onNavigate: (cb) => ipcRenderer.on('navigate', (e, url) => cb(url)),
  onNewTabUrl: (cb) => ipcRenderer.on('new-tab-url', (e, url) => cb(url)),
  onNewTab: (cb) => ipcRenderer.on('new-tab', () => cb()),
  onCloseTab: (cb) => ipcRenderer.on('close-tab', () => cb()),
  onFocusUrlBar: (cb) => ipcRenderer.on('focus-urlbar', () => cb()),
  onReloadTab: (cb) => ipcRenderer.on('reload-tab', () => cb()),
  onForceReloadTab: (cb) => ipcRenderer.on('force-reload-tab', () => cb()),
  onStopLoad: (cb) => ipcRenderer.on('stop-load', () => cb()),
  onToggleBookmarkBar: (cb) => ipcRenderer.on('toggle-bookmark-bar', (e, show) => cb(show)),
  onBookmarkCurrent: (cb) => ipcRenderer.on('bookmark-current', () => cb()),
  onFindInPage: (cb) => ipcRenderer.on('find-in-page', () => cb()),
  onSavePage: (cb) => ipcRenderer.on('save-page', () => cb()),
  onPrintPage: (cb) => ipcRenderer.on('print-page', () => cb()),
  onExtensionBadgeUpdate: (cb) => ipcRenderer.on('extension-badge-update', (e, data) => cb(data)),
  newWindow: () => ipcRenderer.invoke('new-window'),
  newPrivateWindow: () => ipcRenderer.invoke('new-private-window'),
  openDevtools: () => ipcRenderer.invoke('open-devtools'),
  invoke: (channel, ...args) => ipcRenderer.invoke(channel, ...args),

  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  getUpdateStatus: () => ipcRenderer.invoke('get-update-status'),
  downloadUpdate: () => ipcRenderer.invoke('download-update'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  setUpdateFeed: (url) => ipcRenderer.invoke('set-update-feed', url),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (e, data) => cb(data)),
  onMaximizedChanged: (cb) => ipcRenderer.on('window-maximized-changed', (e, isMaximized) => cb(isMaximized)),
});
